kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: money-transfer
nodes:
  - role: control-plane
    image: kindest/node:v1.31.4
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
        protocol: TCP
      - containerPort: 30001
        hostPort: 30001
        protocol: TCP
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
