server:
  port: 8085

spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:postgresql://localhost:5432/transaction_db
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: transaction-service-saga
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

app:
  our-bank-code: "970406"

saga:
  timeout-seconds: 30

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


# ── Observability ──────────────────────────────────────────────
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
logging:
  structured:
    format:
      console: ecs

