server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/v1/accounts/**

        - id: kyc-service
          uri: lb://kyc-service
          predicates:
            - Path=/api/v1/kyc/**

        - id: limit-service
          uri: lb://limit-service
          predicates:
            - Path=/api/v1/limits/**

        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/v1/transactions/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    initial-instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 10