apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "money-transfer.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresql.credentials.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.credentials.password | b64enc }}
