apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: money-transfer
data:
  kong.yml: |
    _format_version: "3.0"
    _transform: true

    services:
      - name: auth-service
        url: http://auth-service:8081
        routes:
          - name: auth-route
            paths:
              - /api/v1/auth
            strip_path: false

      - name: account-service
        url: http://account-service:8082
        routes:
          - name: account-route
            paths:
              - /api/v1/accounts
            strip_path: false

      - name: kyc-service
        url: http://kyc-service:8083
        routes:
          - name: kyc-route
            paths:
              - /api/v1/kyc
            strip_path: false

      - name: limit-service
        url: http://limit-service:8084
        routes:
          - name: limit-route
            paths:
              - /api/v1/limits
            strip_path: false

      - name: transaction-service
        url: http://transaction-service:8085
        routes:
          - name: transaction-route
            paths:
              - /api/v1/transactions
            strip_path: false

    plugins:
      - name: correlation-id
        config:
          header_name: X-Correlation-ID
          generator: uuid
          echo_downstream: true

      - name: rate-limiting
        service: auth-service
        config:
          minute: 30
          policy: local

      - name: rate-limiting
        service: transaction-service
        config:
          minute: 60
          policy: local
