apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-gateway
  namespace: money-transfer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-gateway
  template:
    metadata:
      labels:
        app: kong-gateway
    spec:
      containers:
        - name: kong
          image: kong/kong-gateway:3.9
          ports:
            - containerPort: 8000
              name: proxy
            - containerPort: 8001
              name: admin
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: /kong/kong.yml
            - name: KONG_PROXY_LISTEN
              value: "0.0.0.0:8000"
            - name: KONG_ADMIN_LISTEN
              value: "0.0.0.0:8001"
            - name: KONG_LOG_LEVEL
              value: info
          volumeMounts:
            - name: kong-config
              mountPath: /kong
          readinessProbe:
            exec:
              command: ["kong", "health"]
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["kong", "health"]
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: kong-config
          configMap:
            name: kong-config
