{{- if ne (toString .Values.kong.enabled) "false" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: {{ .Values.namespace }}
  labels:
    app: kong
    {{- include "money-transfer.labels" . | nindent 4 }}
data:
  kong.yml: |
    _format_version: "3.0"
    _transform: true

    services:
    {{- range .Values.kong.routes }}
      - name: {{ .service }}
        url: http://{{ .service }}:{{ .port }}
        routes:
          - name: {{ .service }}-route
            paths:
              - {{ .path }}
            strip_path: false
    {{- end }}

    plugins:
      - name: correlation-id
        config:
          header_name: X-Correlation-ID
          generator: uuid
          echo_downstream: true
{{- end }}
