apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Elasticsearch
    type: elasticsearch
    uid: elasticsearch
    url: http://elasticsearch:9200
    editable: true
    jsonData:
      index: "money-transfer-*"
      timeField: "@timestamp"
      logMessageField: "message"
      logLevelField: "log.level"
      esVersion: "8.0.0"
